//--- Patients ---
export const PROJECT_FETCH = 'PROJECT_FETCH';
export const PROJECT_RESET = 'PROJECT_RESET';
export const PROJECT_ATTACH = 'PROJECT_ATTACH';
export const PROJECT_CLEAR = 'PROJECT_CLEAR';
export const PROJECT_SAVE = 'PROJECT_SAVE';
export const PROJECT_SAVE_FAILD = 'PROJECT_SAVE_FAILD';
export const PROJECT_SAVE_ERROR = 'PROJECT_SAVE_ERROR';
export const PROJECT_DELETE = 'PROJECT_DELETE';
export const PROJECT_DELETE_FAILD = 'PROJECT_DELETE_FAILD';